### ISSUE TITLE
Change the appearance of the village keep based on donations

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/ToroQuest#101]
As you donate to the village lord, at certain tiers, the donations will change the look of the keep.
- donate food and a granary will appear, for each tier, there will be more food in the granary (hay bales, pumpkins, chests with food that can't be taken [or can be but you lose a lot of rep])
- donate lorebooks and a library will appear, with more bookshelves appearing the more books you donate
- donate valuable blocks like gold or diamond blocks and the keep will change from stone to iron, next tier, iron to gold, next tier, gold to diamond

Alternatively, we could add buildings to the village at each of these donation tiers, by checking if every block in the area is a grass, dirt, or sand block.

This will be very difficult because we don't want to erase changes made by the player, but I think it'd be a really cool idea if we could figure it out.  Alternatively, we could maybe put spawn area protection on the blocks that make up the keep, so that you can't break it or add to it by hand.

**Comment by frodare** [comment]
I don't think we should create new structures.  We could generate more entities though, villagers, livestock, guards, and so on.

**Comment by zeriley** [comment]
Yeah, that's a good idea.  I'd really like to add stuff to rooms when you donate.  Like the game Fable 2 had a big vault and the more money you had, the more gold was on the floor of the vault.  It'd be cool to have something like that, but understandably very difficult to achieve.

**Comment by Syndaryl** [comment]
I do like upgrading the keep; I played the heck out of Overlord and Overlord 2 and upgrading my keep (and having piles of treasure in my treasury) was a big feature.
Suggestion: Create a decorative "pile of gold coins" block that is sub-slab size and that the player interacts with as if it were a carpet. Make a big reputation hit for stealing them.
Have a treasury room that initially is carpeted. As more donations are made, replace random carpet-layer block with "pile of gold coins" block. If the player stole the carpet, it just takes that spot. If the player didn't steal the carpet, it replaces the carpet.
Add a recipe to smelt one "pile of gold coins" square into a gold ingot, because inevitably some player will steal them.
If you want another tier, add "pile of gold coins and gems" that smelts into an emerald or diamond.

Give the lord a throne (as a structure made out of blocks in the usual Minecraft way), and update the materials its made out of. Might need to add new decorative blocks to do this.

Upgrade/augment lighting fixtures from torches on the wall to "Candelabra" structures hanging from the ceiling - wood fence/iron fence/netherbrick fence + torches, and then glowstone block, and trapdoors lantern, something like that
