### ISSUE TITLE
Fire Sword Ideas

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#108]
- Make it less powerful ... or

- Make it do less damage against blazes (or maybe all nether mobs?)
- Have it dropped cooked meat when killing animals
- Ineffective under water (or damaged when used under water or in rain?)

**Comment by zeriley** [comment]
I actually haven't used the fire sword yet, so I don't know what needs balanced about it.  I like the ideas, though.  I wouldn't want it to be damaged in rain, though, just because then you always need to carry around two swords.  If you know you'll be going into the Nether or underwater, then you can think ahead and change out swords, so that's not a big deal, but since it can rain at any time, you would always need a second sword to use if it starts raining.
