### ISSUE TITLE
[1.11.2-2] crashes dedicated Forge 1.11.2 build 2226 on player connect

### ISSUE THREAD

**Issue by kreezxil** [ToroCraft/ToroQuest#111]
Notes:
     don't blame this on sponge

crash report:
https://gist.github.com/be439dbaca565d0b81b3f46f66729f70

fml server latest:
https://gist.github.com/0b230fad10ffe07085063b12528147d8

**Comment by frodare** [comment]
I will look into why `Random.nextInt` is calling a negative number.

**Comment by frodare** [comment]
@kreezxil do you have a modpack you are using that I can download to easily reproduce this problem?

**Comment by frodare** [comment]
I think one of the other mods is doing something with `villager.populateBuyingList()` that is incompatible with the shopkeeper entity. I am thinking it will be pretty easy to fix by overriding that method since the shopkeeper doesn't need it anyway.  @kreezxil if that works out I can send you a link to a pre-release build to test if you like, so that I can verify the problem has been fixed.

**Comment by frodare** [comment]
I have made some changes to hopefully fix this issue. However since I have no way to test it I can't know for sure.  If you would like to test it, download this zip file rename the extension to `.jar` and give it a shot.  It is built against forge 2226.  If the bug is still there let me know and I will reopen this issue.

[toroquest-1.11.2-2-a2.zip](https://github.com/ToroCraft/ToroQuest/files/740855/toroquest-1.11.2-2-a2.zip)
