### ISSUE TITLE
1.11.2-3.0 crashes dedicated Forge 1.11.2 build 2227 when npc attacks toro

### ISSUE THREAD

**Issue by kreezxil** [ToroCraft/ToroQuest#119]
Notes:
     an npc was attacking the toro this time!

crash report:
https://gist.github.com/009d649a01555f088718ab87ba41779a

fml server latest:
https://gist.github.com/6300f3d6b581f9c0d370f9fe1d9c00f7

**Comment by frodare** [comment]
How dare he!  I have not figured out a way to load a modpack from within my build environment.  I have one more "blindfolded" patch I can try though.  If I have time I will make a new build tonight and upload it.  If that doesn't work, I will need how help figuring out which mod is not playing nicely with TQ so that I can load it independently and find a fix that I can verify works.

**Comment by frodare** [comment]
Duplicate issue: https://github.com/ToroCraft/ToroQuest/issues/116
