### ISSUE TITLE
Suggestion: Setting Nation

### ISSUE THREAD

**Issue by HypnoPants** [ToroCraft/ToroQuest#129]
Basically, the ability to set a point at which a new nation will form.

I love how a village will have a nation-system for reputation, spawning sentries and guards, etc...

I would love to see the ability to set where a nation was, and building the village myself.

**Comment by frodare** [comment]
Another great idea.  We have actually talked about this one.  In the last version I added the ability to create Guards and Village Lords by converting them from Zombie Villagers.  I need to add that to the wiki.  I think it would be cool that once you created a village lord that was not in a province you have the ability to create a new province of the civilization and name of your choice.  I would add a rep boost and achievement too to add to the game play.  I think this is pretty doable, if it comes together quick enough I will get it in the next version.

**Comment by zeriley** [comment]
I like this idea and it sparked an idea for another way to do this, @frodare.  At the Ally rep level, the lord may give you a quest to go plant a flag and start a new village for the province.  It would have to be 200 blocks from any village lord so that we don't overwrite any villages.  Then you can create a village lord in that new village and he will be able to give you quests.  Maybe a new friend tier called Founder if you create a village and create a village lord for it.

Needs polishing, but what do you think?

**Comment by frodare** [comment]
@zeriley ah, nice, love it.  That would be easier to code to!  I think we might want to spawn a village lord when the flag (banner) is placed for simplicity.  Spawning lords could be reserved for adding additional lords or replacing them.

**Comment by zeriley** [comment]
Yeah, I was thinking that, but then wasn't sure how his AI would behave.  If you planted the flag, a village lord appeared, and then he just walked away, that'd be a problem.  But, I'm sure we could fix that if that's the case.

**Comment by HypnoPants** [comment]
... I'm enjoying giving good ideas :P It's more of the dynamic of the people I play with.
