### ISSUE TITLE
ToroQuest Mobs Won't Spawn

### ISSUE THREAD

**Issue by PugLyf** [ToroCraft/ToroQuest#149]
I am using the Aether Legacy mod, and in another thread, I saw the response saying to set specific entity names to true. Doing so makes it so none of the mobs spawn with villages though, only from spawn eggs. I don't believe this is what the command is intended to do, but I could be wrong.

**Comment by frodare** [comment]
They should still spawn, but only for newly created villages.  That is why the option is defaulted to false, because setting that option to true removes all ToroQuest mobs from the world. If the world is started with with that option, however, it shouldn't make a difference. I am thinking about defaulting that option to true if I upgrade this mod to 1.12 when it comes out.

**Comment by PugLyf** [comment]
No, I generate a completely new world and nothing spawns in, but only if it is set to true. I've been playing around with it and when it is set to false everything spawns.

**Comment by frodare** [comment]
Strange, I will have to take a look at that then, that is certainly not what it is suppose to do.

**Comment by PugLyf** [comment]
Alright, let me know if there is any info you need from me to help you.

**Comment by frodare** [comment]
I forgot to ask, which version of the mod are you using?

**Comment by PugLyf** [comment]
1.11.2

**Comment by frodare** [comment]
Not sure how I missed this, thanks for bringing it to my attention! I will try to get a new release out in a few days.

**Comment by PugLyf** [comment]
Awesome! Thanks.
