### ISSUE TITLE
Shopkeeper

### ISSUE THREAD

**Issue by Bjarka1** [ToroCraft/ToroQuest#155]
I can't buy anything from the shopkeeper IF the price is ABOVE one stack of emeralds.

And some of the stuff they are selling i`s REALLY great so you want it! :)

**Comment by frodare** [comment]
LOL, yes that was a bit of a goof.  This bug is reported here: 

Unable to buy expensive items from shopkeeper due to emerald stack limit #112

Thanks for letting us know though! For now you need to work on getting your rep higher so that the prices get cheaper or use the Villager Market as a work around suggested by @Zygus42

**Comment by Bjarka1** [comment]
Ah, sorry for posting something that's already here. Great though that better rep makes it cheaper. This mod is really well thought out. :)
