### ISSUE TITLE
Random classes and textures for guards

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/ToroQuest#168]
guards are the same thing, must be more dynamic, some guards holding axes, bows, woman guards, alchemists aka friendly witches (but put some thing unique for not be like MCA)

https://mods.curse.com/mc-mods/minecraft/257330-toroquest?comment=5

**Comment by NekoAmps** [comment]
I wouldn't try for "woman guards" specifically; try playing around with the androgyny of different guard skins, so some seem clearly male or female but others seem like they could go either way. Definitely use both Steve and Alex models (Steve has an arm width of 4 pixels, Alex's is 3 pixels); please avoid block boobs. Remember a wide variety of skin tones while you're at it!

For classes, since we already have guards and scouts, distinctively, it would be great to add a ranger who uses bow & arrow from afar but switches to an axe or sword up close. But vanilla MC doesn't provide much to add a variety of kits with, so I wouldn't focus too much on adding many NPC classes.
