### ISSUE TITLE
Backport #147 to 1.10.2

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#177]
https://minecraft.curseforge.com/projects/toroquest?comment=109
Would you be able to implement a fix for the sentries spawning in the nether for MC 1.10.2?  I see there was a report of the issue, but the fix appears to be only for MC 1.11.2.  Thank you.
~User_33963516

**Comment by frodare** [comment]
#147

**Comment by Jo-Mamma75** [comment]
I see closing Github issues has been a little slow as of late but any update on this particular issue?  The 1.10.2 version hasn't had an update since April 2017 and the 1.11/1.12 versions haven't been updated since the Summer.  Would it be fair to assume that the above requested fix will not happen?

**Comment by frodare** [comment]
@Jo-Mamma75 Yes, torocraft development has stopped because the developers have moved on to other things.
