### ISSUE TITLE
The Toro Mob

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#2]
Create a new bull like mob that will spawn randomly around cows and will aggressively attack when cows are killed in his vicinity.

**Comment by Wing01** [comment]
Spawner needs to be fixed

**Comment by zeriley** [comment]
Some ideas to make the Toro beneficial and introduce a risk-reward for keeping him around, rather than killing him from a distance and removing all added gameplay elements:
- presence of Toro decreases other cows' DTF meter
- alternatively, the Toro could be ready for breeding 30 seconds after the last breeding, but could not breed with another Toro (or he COULD breed with another Toro, but it wouldn't produce a baby, which could introduce a balance so you don't keep too many Toros around)
- Toros will attack hostile mobs that get too close to a cow (could cause issues if they attack creepers, though...)

**Comment by zeriley** [comment]
Look into using EntityEvent.EntityConstructing rather than EntityJoinWorldEvent to fix toro spawning issue

**Comment by zeriley** [comment]
For now, our solution will be to write a boolean to the NBT that indicates that the cow is not a new spawn, then will check that boolean before generating a new Toro.  Will also need to check if the cow is a result of breeding, if possible.

**Comment by zeriley** [comment]
Fixed spawning issue.  Leaving issue open to discuss toro features.
